/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeRouteImport } from './routes/me'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesVehicle_listingRouteImport } from './routes/vehicles/vehicle_listing'
import { Route as VehiclesSearchRouteImport } from './routes/vehicles/search'
import { Route as VehiclesMyVehiclesRouteImport } from './routes/vehicles/my-vehicles'
import { Route as VehiclesIdRouteImport } from './routes/vehicles/$id'
import { Route as UserWalletRouteImport } from './routes/user/wallet'
import { Route as UserSubscriptionRouteImport } from './routes/user/subscription'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserMyBookingsRouteImport } from './routes/user/my-bookings'
import { Route as UserChatRouteImport } from './routes/user/chat'
import { Route as AuthVerifyOtpForgotRouteImport } from './routes/auth/verify-otp-forgot'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth/verify-otp'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthConfirmPasswordRouteImport } from './routes/auth/confirm-password'
import { Route as AuthAdminLoginRouteImport } from './routes/auth/admin-login'
import { Route as AdminVehicleManagementIndexRouteImport } from './routes/admin/vehicle-management/index'
import { Route as AdminUserManagementIndexRouteImport } from './routes/admin/user-management/index'
import { Route as AdminSubscriptionManagementIndexRouteImport } from './routes/admin/subscription-management/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminCategoryManagementIndexRouteImport } from './routes/admin/category-management/index'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin/bookings/index'
import { Route as AdminBookingManagementIndexRouteImport } from './routes/admin/booking-management/index'
import { Route as VehiclesEditIdRouteImport } from './routes/vehicles/edit/$id'
import { Route as AdminVehicleManagementIdRouteImport } from './routes/admin/vehicle-management/$id'

const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesVehicle_listingRoute = VehiclesVehicle_listingRouteImport.update({
  id: '/vehicles/vehicle_listing',
  path: '/vehicles/vehicle_listing',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesSearchRoute = VehiclesSearchRouteImport.update({
  id: '/vehicles/search',
  path: '/vehicles/search',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesMyVehiclesRoute = VehiclesMyVehiclesRouteImport.update({
  id: '/vehicles/my-vehicles',
  path: '/vehicles/my-vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIdRoute = VehiclesIdRouteImport.update({
  id: '/vehicles/$id',
  path: '/vehicles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UserWalletRoute = UserWalletRouteImport.update({
  id: '/user/wallet',
  path: '/user/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSubscriptionRoute = UserSubscriptionRouteImport.update({
  id: '/user/subscription',
  path: '/user/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UserMyBookingsRoute = UserMyBookingsRouteImport.update({
  id: '/user/my-bookings',
  path: '/user/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const UserChatRoute = UserChatRouteImport.update({
  id: '/user/chat',
  path: '/user/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyOtpForgotRoute = AuthVerifyOtpForgotRouteImport.update({
  id: '/verify-otp-forgot',
  path: '/verify-otp-forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmPasswordRoute = AuthConfirmPasswordRouteImport.update({
  id: '/confirm-password',
  path: '/confirm-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminLoginRoute = AuthAdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminVehicleManagementIndexRoute =
  AdminVehicleManagementIndexRouteImport.update({
    id: '/vehicle-management/',
    path: '/vehicle-management/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminUserManagementIndexRoute =
  AdminUserManagementIndexRouteImport.update({
    id: '/user-management/',
    path: '/user-management/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSubscriptionManagementIndexRoute =
  AdminSubscriptionManagementIndexRouteImport.update({
    id: '/subscription-management/',
    path: '/subscription-management/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoryManagementIndexRoute =
  AdminCategoryManagementIndexRouteImport.update({
    id: '/category-management/',
    path: '/category-management/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingManagementIndexRoute =
  AdminBookingManagementIndexRouteImport.update({
    id: '/booking-management/',
    path: '/booking-management/',
    getParentRoute: () => AdminRoute,
  } as any)
const VehiclesEditIdRoute = VehiclesEditIdRouteImport.update({
  id: '/vehicles/edit/$id',
  path: '/vehicles/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehicleManagementIdRoute =
  AdminVehicleManagementIdRouteImport.update({
    id: '/vehicle-management/$id',
    path: '/vehicle-management/$id',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/me': typeof MeRoute
  '/auth/admin-login': typeof AuthAdminLoginRoute
  '/auth/confirm-password': typeof AuthConfirmPasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/auth/verify-otp-forgot': typeof AuthVerifyOtpForgotRoute
  '/user/chat': typeof UserChatRoute
  '/user/my-bookings': typeof UserMyBookingsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/subscription': typeof UserSubscriptionRoute
  '/user/wallet': typeof UserWalletRoute
  '/vehicles/$id': typeof VehiclesIdRoute
  '/vehicles/my-vehicles': typeof VehiclesMyVehiclesRoute
  '/vehicles/search': typeof VehiclesSearchRoute
  '/vehicles/vehicle_listing': typeof VehiclesVehicle_listingRoute
  '/admin/vehicle-management/$id': typeof AdminVehicleManagementIdRoute
  '/vehicles/edit/$id': typeof VehiclesEditIdRoute
  '/admin/booking-management': typeof AdminBookingManagementIndexRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/category-management': typeof AdminCategoryManagementIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/subscription-management': typeof AdminSubscriptionManagementIndexRoute
  '/admin/user-management': typeof AdminUserManagementIndexRoute
  '/admin/vehicle-management': typeof AdminVehicleManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/me': typeof MeRoute
  '/auth/admin-login': typeof AuthAdminLoginRoute
  '/auth/confirm-password': typeof AuthConfirmPasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/auth/verify-otp-forgot': typeof AuthVerifyOtpForgotRoute
  '/user/chat': typeof UserChatRoute
  '/user/my-bookings': typeof UserMyBookingsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/subscription': typeof UserSubscriptionRoute
  '/user/wallet': typeof UserWalletRoute
  '/vehicles/$id': typeof VehiclesIdRoute
  '/vehicles/my-vehicles': typeof VehiclesMyVehiclesRoute
  '/vehicles/search': typeof VehiclesSearchRoute
  '/vehicles/vehicle_listing': typeof VehiclesVehicle_listingRoute
  '/admin/vehicle-management/$id': typeof AdminVehicleManagementIdRoute
  '/vehicles/edit/$id': typeof VehiclesEditIdRoute
  '/admin/booking-management': typeof AdminBookingManagementIndexRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/category-management': typeof AdminCategoryManagementIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/subscription-management': typeof AdminSubscriptionManagementIndexRoute
  '/admin/user-management': typeof AdminUserManagementIndexRoute
  '/admin/vehicle-management': typeof AdminVehicleManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/me': typeof MeRoute
  '/auth/admin-login': typeof AuthAdminLoginRoute
  '/auth/confirm-password': typeof AuthConfirmPasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/auth/verify-otp-forgot': typeof AuthVerifyOtpForgotRoute
  '/user/chat': typeof UserChatRoute
  '/user/my-bookings': typeof UserMyBookingsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/subscription': typeof UserSubscriptionRoute
  '/user/wallet': typeof UserWalletRoute
  '/vehicles/$id': typeof VehiclesIdRoute
  '/vehicles/my-vehicles': typeof VehiclesMyVehiclesRoute
  '/vehicles/search': typeof VehiclesSearchRoute
  '/vehicles/vehicle_listing': typeof VehiclesVehicle_listingRoute
  '/admin/vehicle-management/$id': typeof AdminVehicleManagementIdRoute
  '/vehicles/edit/$id': typeof VehiclesEditIdRoute
  '/admin/booking-management/': typeof AdminBookingManagementIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/category-management/': typeof AdminCategoryManagementIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/subscription-management/': typeof AdminSubscriptionManagementIndexRoute
  '/admin/user-management/': typeof AdminUserManagementIndexRoute
  '/admin/vehicle-management/': typeof AdminVehicleManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/me'
    | '/auth/admin-login'
    | '/auth/confirm-password'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/auth/verify-otp-forgot'
    | '/user/chat'
    | '/user/my-bookings'
    | '/user/profile'
    | '/user/subscription'
    | '/user/wallet'
    | '/vehicles/$id'
    | '/vehicles/my-vehicles'
    | '/vehicles/search'
    | '/vehicles/vehicle_listing'
    | '/admin/vehicle-management/$id'
    | '/vehicles/edit/$id'
    | '/admin/booking-management'
    | '/admin/bookings'
    | '/admin/category-management'
    | '/admin/dashboard'
    | '/admin/subscription-management'
    | '/admin/user-management'
    | '/admin/vehicle-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/me'
    | '/auth/admin-login'
    | '/auth/confirm-password'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/auth/verify-otp-forgot'
    | '/user/chat'
    | '/user/my-bookings'
    | '/user/profile'
    | '/user/subscription'
    | '/user/wallet'
    | '/vehicles/$id'
    | '/vehicles/my-vehicles'
    | '/vehicles/search'
    | '/vehicles/vehicle_listing'
    | '/admin/vehicle-management/$id'
    | '/vehicles/edit/$id'
    | '/admin/booking-management'
    | '/admin/bookings'
    | '/admin/category-management'
    | '/admin/dashboard'
    | '/admin/subscription-management'
    | '/admin/user-management'
    | '/admin/vehicle-management'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/me'
    | '/auth/admin-login'
    | '/auth/confirm-password'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/auth/verify-otp-forgot'
    | '/user/chat'
    | '/user/my-bookings'
    | '/user/profile'
    | '/user/subscription'
    | '/user/wallet'
    | '/vehicles/$id'
    | '/vehicles/my-vehicles'
    | '/vehicles/search'
    | '/vehicles/vehicle_listing'
    | '/admin/vehicle-management/$id'
    | '/vehicles/edit/$id'
    | '/admin/booking-management/'
    | '/admin/bookings/'
    | '/admin/category-management/'
    | '/admin/dashboard/'
    | '/admin/subscription-management/'
    | '/admin/user-management/'
    | '/admin/vehicle-management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MeRoute: typeof MeRoute
  UserChatRoute: typeof UserChatRoute
  UserMyBookingsRoute: typeof UserMyBookingsRoute
  UserProfileRoute: typeof UserProfileRoute
  UserSubscriptionRoute: typeof UserSubscriptionRoute
  UserWalletRoute: typeof UserWalletRoute
  VehiclesIdRoute: typeof VehiclesIdRoute
  VehiclesMyVehiclesRoute: typeof VehiclesMyVehiclesRoute
  VehiclesSearchRoute: typeof VehiclesSearchRoute
  VehiclesVehicle_listingRoute: typeof VehiclesVehicle_listingRoute
  VehiclesEditIdRoute: typeof VehiclesEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/vehicle_listing': {
      id: '/vehicles/vehicle_listing'
      path: '/vehicles/vehicle_listing'
      fullPath: '/vehicles/vehicle_listing'
      preLoaderRoute: typeof VehiclesVehicle_listingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/search': {
      id: '/vehicles/search'
      path: '/vehicles/search'
      fullPath: '/vehicles/search'
      preLoaderRoute: typeof VehiclesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/my-vehicles': {
      id: '/vehicles/my-vehicles'
      path: '/vehicles/my-vehicles'
      fullPath: '/vehicles/my-vehicles'
      preLoaderRoute: typeof VehiclesMyVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$id': {
      id: '/vehicles/$id'
      path: '/vehicles/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof VehiclesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/wallet': {
      id: '/user/wallet'
      path: '/user/wallet'
      fullPath: '/user/wallet'
      preLoaderRoute: typeof UserWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/subscription': {
      id: '/user/subscription'
      path: '/user/subscription'
      fullPath: '/user/subscription'
      preLoaderRoute: typeof UserSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/my-bookings': {
      id: '/user/my-bookings'
      path: '/user/my-bookings'
      fullPath: '/user/my-bookings'
      preLoaderRoute: typeof UserMyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/chat': {
      id: '/user/chat'
      path: '/user/chat'
      fullPath: '/user/chat'
      preLoaderRoute: typeof UserChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-otp-forgot': {
      id: '/auth/verify-otp-forgot'
      path: '/verify-otp-forgot'
      fullPath: '/auth/verify-otp-forgot'
      preLoaderRoute: typeof AuthVerifyOtpForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/confirm-password': {
      id: '/auth/confirm-password'
      path: '/confirm-password'
      fullPath: '/auth/confirm-password'
      preLoaderRoute: typeof AuthConfirmPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/admin-login': {
      id: '/auth/admin-login'
      path: '/admin-login'
      fullPath: '/auth/admin-login'
      preLoaderRoute: typeof AuthAdminLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/vehicle-management/': {
      id: '/admin/vehicle-management/'
      path: '/vehicle-management'
      fullPath: '/admin/vehicle-management'
      preLoaderRoute: typeof AdminVehicleManagementIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/user-management/': {
      id: '/admin/user-management/'
      path: '/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AdminUserManagementIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscription-management/': {
      id: '/admin/subscription-management/'
      path: '/subscription-management'
      fullPath: '/admin/subscription-management'
      preLoaderRoute: typeof AdminSubscriptionManagementIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/category-management/': {
      id: '/admin/category-management/'
      path: '/category-management'
      fullPath: '/admin/category-management'
      preLoaderRoute: typeof AdminCategoryManagementIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/booking-management/': {
      id: '/admin/booking-management/'
      path: '/booking-management'
      fullPath: '/admin/booking-management'
      preLoaderRoute: typeof AdminBookingManagementIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vehicles/edit/$id': {
      id: '/vehicles/edit/$id'
      path: '/vehicles/edit/$id'
      fullPath: '/vehicles/edit/$id'
      preLoaderRoute: typeof VehiclesEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicle-management/$id': {
      id: '/admin/vehicle-management/$id'
      path: '/vehicle-management/$id'
      fullPath: '/admin/vehicle-management/$id'
      preLoaderRoute: typeof AdminVehicleManagementIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminVehicleManagementIdRoute: typeof AdminVehicleManagementIdRoute
  AdminBookingManagementIndexRoute: typeof AdminBookingManagementIndexRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminCategoryManagementIndexRoute: typeof AdminCategoryManagementIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminSubscriptionManagementIndexRoute: typeof AdminSubscriptionManagementIndexRoute
  AdminUserManagementIndexRoute: typeof AdminUserManagementIndexRoute
  AdminVehicleManagementIndexRoute: typeof AdminVehicleManagementIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminVehicleManagementIdRoute: AdminVehicleManagementIdRoute,
  AdminBookingManagementIndexRoute: AdminBookingManagementIndexRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminCategoryManagementIndexRoute: AdminCategoryManagementIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminSubscriptionManagementIndexRoute: AdminSubscriptionManagementIndexRoute,
  AdminUserManagementIndexRoute: AdminUserManagementIndexRoute,
  AdminVehicleManagementIndexRoute: AdminVehicleManagementIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthAdminLoginRoute: typeof AuthAdminLoginRoute
  AuthConfirmPasswordRoute: typeof AuthConfirmPasswordRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
  AuthVerifyOtpForgotRoute: typeof AuthVerifyOtpForgotRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminLoginRoute: AuthAdminLoginRoute,
  AuthConfirmPasswordRoute: AuthConfirmPasswordRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
  AuthVerifyOtpForgotRoute: AuthVerifyOtpForgotRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MeRoute: MeRoute,
  UserChatRoute: UserChatRoute,
  UserMyBookingsRoute: UserMyBookingsRoute,
  UserProfileRoute: UserProfileRoute,
  UserSubscriptionRoute: UserSubscriptionRoute,
  UserWalletRoute: UserWalletRoute,
  VehiclesIdRoute: VehiclesIdRoute,
  VehiclesMyVehiclesRoute: VehiclesMyVehiclesRoute,
  VehiclesSearchRoute: VehiclesSearchRoute,
  VehiclesVehicle_listingRoute: VehiclesVehicle_listingRoute,
  VehiclesEditIdRoute: VehiclesEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
